spring:
  h2:
    console:
      enabled: true
      path: /h2/console
      settings:
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
  jpa:
    hibernate:      ddl-auto: create-drop
    show-sql: true
    properties:      hibernate:
        format_sql: true